
public enum EnumAudioCombat
{
    None,
    //战斗号角
    battle_viking_horn_call_close_01,
    battle_viking_horn_call_close_02,
    //放屁
    cartoon_squirt_04,
    //金币
    cash_register_open_coins_cha_ching_01,
    //提醒
    chime_bell_positive_ring_01,
    chime_tinkle_wood_bell_positive_08,
    //金币的声音
    coin_bag_ring_gemstone_item_15,
    //跑步的声音
    footstep_grass_run_01,
    footstep_grass_run_02,
    footstep_grass_run_03,
    footstep_grass_run_04,
    footstep_grass_run_05,
    footstep_grass_run_06,
    footstep_grass_run_07,
    footstep_grass_run_08,
    footstep_grass_run_09,
    footstep_grass_run_10,
    //挨打
    GRUNT_Male_Hurt_01_mono,
    GRUNT_Male_Hurt_02_mono,
    GRUNT_Male_Hurt_03_mono,
    GRUNT_Male_Hurt_04_mono,
    //攻击时的武器声音
    IMPACT_ShootEmUp_Medium_01_RR01_mono,
    IMPACT_ShootEmUp_Medium_01_RR02_mono,
    IMPACT_ShootEmUp_Medium_01_RR03_mono,
    IMPACT_ShootEmUp_Medium_02_RR01_mono,
    IMPACT_ShootEmUp_Medium_02_RR02_mono,
    IMPACT_ShootEmUp_Medium_02_RR03_mono,
    IMPACT_ShootEmUp_Medium_03_RR01_mono,
    IMPACT_ShootEmUp_Medium_03_RR02_mono,
    IMPACT_ShootEmUp_Medium_03_RR03_mono,
    IMPACT_ShootEmUp_Medium_04_RR01_mono,
    IMPACT_ShootEmUp_Medium_04_RR02_mono,
    IMPACT_ShootEmUp_Medium_04_RR03_mono,
    IMPACT_ShootEmUp_Medium_05_RR01_mono,
    IMPACT_ShootEmUp_Medium_05_RR02_mono,
    IMPACT_ShootEmUp_Medium_05_RR03_mono,
    IMPACT_ShootEmUp_Medium_06_RR01_mono,
    IMPACT_ShootEmUp_Medium_06_RR02_mono,
    IMPACT_ShootEmUp_Medium_06_RR03_mono,
    IMPACT_ShootEmUp_Medium_07_RR01_mono,
    IMPACT_ShootEmUp_Medium_07_RR02_mono,
    IMPACT_ShootEmUp_Medium_07_RR03_mono,
    //背景音乐
    music_calm_green_lake_serenade,
    //失败的堕落声音
    MUSIC_EFFECT_Orchestral_Brass_Negative_01_stereo,
    //胜利的高昂声音
    MUSIC_EFFECT_Orchestral_Brass_Positive_11_stereo,
    //背景声音,紧张的作战氛围
    music_epic_orchestral_bg_underscore,
    //背景,放松愉快的诡异
    music_fun_funky_whistle_groove_loop,
    //背景,欢快的,小鹿乱撞,节奏快
    music_happy_high_pop_advertising_jingle,
    //背景,低沉,缓和
    music_harp_peaceful_loop,
    //背景,童真,调子有点高
    music_kids_play_loop_01,
    //攻击,嘿
    VOICE_Martial_Art_Shout_01_mono,
    //挨打,啊
    VOICE_Martial_Art_Shout_02_mono,
    VOICE_Martial_Art_Shout_03_mono,
    VOICE_Martial_Art_Shout_04_mono,
    VOICE_Martial_Art_Shout_05_mono,
    VOICE_Martial_Art_Shout_06_mono,
    VOICE_Martial_Art_Shout_07_mono,
    VOICE_Martial_Art_Shout_08_mono,
    VOICE_Martial_Art_Shout_09_mono,
}
