
/// <summary>
/// 翻译,单词
/// </summary>
public enum EnumLanguageWords
{
    Prepare,//准备
    Save,//存档
    Settings,//设置
    GameIntroduction,//游戏介绍
    Load,//读取
    Delete,//删除
    None,//无
    ModifyNickname,//修改昵称
    Nickname,//昵称
    RandomMap,//随机地图
    Map,//地图
    Back,//返回
    StartGame,//开始游戏
    Sound,//声音
    Audio,//音效
    Menu,//菜单
    GameDuration,//游戏时长
    GameDate,//游戏日期
    Tasks,//任务
    Warehouse,//仓库
    BattleQueue,//战斗队列
    Backpack,//背包
    Organize,//整理
    Move,//移动
    MoveTo,//移动到
    PleaseCTFT,//请完成以下任务
    CurrentMailCount,//目前的邮件数量
    Rewards,//奖励
    DismissEmployees,//解雇员工
    AnnualOIA,//每年的产量约为
    AnnualCIA,//每年消耗量约为
    Days,//天
    Demolish,//拆除
    Yield,//产量
    Planting,//种植
    InsufficientConsumables,//消耗品不足
    Breeding,//养殖
    NoEmployeesMining,//没有员工采矿
    Mining,//正在采矿
    Smelting,//冶炼
    InsufficientCoins,//金币不足
    MaximumSQR,//已经达到最大合成个数
    NumericalError,//数值出错
    ThisLCBP,//该地无法购买
    EmployEmployees,//雇佣员工
    Employ,//雇佣
    Change,//更改
    Consume,//消耗
    SelectTPTBM,//选择产出的产品
    SelectTPTBC,//选择消耗的产品
    Produce,//生产
    RequiredMaterials,//需要的材料
    EarnedCoins,//赚取的金币
    CurrentQuantity,//当前数量
    UnitPrice,//单价
    RequiredCTP,//购买所需金币
    Enter,//进入
    EnemyTeam,//敌人队伍
    SmallMonster,//小怪
    ClearanceReward,//通关奖励
    Battle,//战斗
    BattleDuration,//战斗时长
    RemainingTeam,//剩余队伍
    Defeated,//战败
    Confirm,//确定
    Farm,//农园
    Pasture,//牧园
    Workshop,//工坊
    Other,//其他
    ProductName,//产品名称
    Dismiss,//解雇
    NumberOfPeople,//人数
    Level,//等级
    PleaseEAN,//请输入昵称
    NicknameCBE,//昵称不能为空
    ReceiveReward,//领取奖励
    ProceedTNR,//是否进入下一回合
    SmallMQ,//小怪队列
    SmallMT,//小怪队伍
    Team,//队伍
    Queue,//队列
    InstanceDetails,//副本详情
    DeleteSave,//删除存档
    OutgoingWarehouse,//出仓
    IncomingWarehouse,//入仓
    PleaseSelectQuantity,//请选择数量
    WarehouseCapacity,//仓储容量
    SpentCoins,//花费的金币
    QuantityForSale,//出售数量
    Bankruptcy,//破产
    BankruptcyCountdown,//破产倒计时
    ReturnTLogin,//返回登陆
    SaveGame,//保存游戏
    ExitGame,//离开游戏
    FarmMerchant,//农场商人
    PurchasingMerchant,//收购商人
    ConfirmChanges,//确定更改
    RareItemMerchant,//稀有物品商人
    Go,//前往
    Sell,//出售
    Purchase,//购买
    QuantityToPurchase,//购买数量
    TotalPrice,//购买总价
    EndTheBattle,//结束战斗
    Obstacle,//障碍物
    TaskName,//任务名称
    Completed,//已完成
    TaskCompleted,//已完成任务
    TheIINITB,//背包中,没有该物品!
    DoYWTRTL,//是否返回登陆？
    DoYWTETG,//是否退出游戏？
    DoYWTBL,//是否购买土地？
    InsufficientQOTIITB,//背包中，该物品数量不足！
    GameSaved,//游戏已保存
    Land,//土地
    Wasteland,//荒地
    Receive,//领取
    View,//查看
    Scrolls,//卷轴(武器合成材料单)
    ThereANAE,//没有空闲的员工
    IsTBTBD,//是否拆除建筑？
    Refresh,//刷新
    Restock,//进货
    PleaseConstruct,//请建造:
    GoldCoins,//金币
    MaximumCOFC,//金币最大容量：
    Obtainable,//可获得：
    Recyclable,//可回收：
    SellTPOL,//出售这块土地。
    SellingTPOLWYRGC,//出售这块土地，可回收金币：
    QuantityAFSTY,//今年可出售数量：
    Penalty,//罚金：
    UncompletedPenalty,//未完成处罚：
    CompletedReward,//已完成奖励:
    TraditionalChinese,//繁体中文
    SimplifiedChinese,//简体中文
    English,//英语
    Japan,//日语
    BackgroundMusic,//背景音乐
    WindowResolution,//窗口分辨率
    FullScreen,//全屏
    Wan,//万
    Yi,//亿
    Thousand,//千
    Million,//百万
    Billion,//十亿
    Upgrade,//升级
    Grade,//等级
    Capacity,//容量
    TheMLHBR,//已经达到最大等级。
    RequiredMAC,//需要的材料和金币。
    Random,//随机
    AnnualRevenue,//每年的收益
    TheMWCHB,//已经达到最大仓库容量！
    ItemsProduced,//生产的物品：
    CancelConstruction,
    ConstructionCost,
}
