
/// <summary>
/// 翻译,句子
/// </summary>
public enum EnumLanguageStatement
{
    None,
    HarvestNumsDays,//每7天产出6苹果
    HarvestNumsDay,//每天产出7苹果
    ObtainNumDays,//每7天产出1苹果
    ObtainNumDay,//每天产出1苹果
    ConsumeNumsDays,//每7天消耗6苹果
    ConsumeNumsDay,//每天消耗7苹果
    ConsumeNumDays,//每7天消耗1苹果
    ConsumeNumDay,//每天消耗1苹果
    TakesComplete,//需要1天完成
    RequiresFinish,//需要6天完成
    InsufficientQOTFIITI,//背包中,以下物品数量不足:
    NicknameSNELOC,//昵称不能超过6个字母或汉子
    TheFRHBSTYE,//以下奖励,已发送邮箱
    LimitedBSWYLTOI,//背包空间不足,是否整理?
    OutputQIPEA,//输出数量为0,请重新输入
    MoveFTITTW,//将背包中的6个苹果移动到仓库
    TransferFTWTB,//将仓库中的6个苹果移动到背包
    MoveTITB,//将物品移动到背包
    MoveTITTW,//将物品移动到仓库
    InsufficientGUTMTP,//金币不足，无法购买
    NotEBSUTMTP,//背包空间不足,无法购买
    QuantityCPTA,//数量变动,请重试!
    NoEITBQ,//战斗队列中没有员工
    HeadTLMPACT,//前往“某地”，寻找任务点，并通关任务点。
    ResolveHIIBTCE,//请在倒计时结束前，处理负债累累的问题！
    ArchivesAFPDOSFATCSA,//存档已满,请删除一个存档,再点击保存
    JanuaryOEY,//每年的1月1日
    RestockOTFDOTM,//每月的1日进货
    RestockOJEY,//每年6月2日进货
    ToEYNTDTBO,//击败某地(地名)的boss，才能进入
    WhenYHANBYWGBATGWBO,//当您的资金为负时,将会破产,游戏就会结束
    TheBDNHESPSIO,//背包空间不足,请整理!
    RewardFI,//1个物品奖励
    RewardFIs,//10个物品奖励
    FailureTCTTIPOGC,//没有完成“***”任务，处罚100金币。
    EmployeesAAWDWCTTLTP,//有6名员工在工作，拆除后员工将离开岗位，并失去这些员工。
    AfterDEWBL,//拆除后，将失去6名员工
    SellingIETAQLIAT,//出售物品超过每年的数量限制,支付500金币的税金。
    ItemsSWAUPBGCAQ,//出售的物品单价没有超过10金币，且没有超过5000的数量限制，不用交税金。
    CompletionOATAGCAAPOG,//10个任务，完成所有任务可获100金币，没完成任务处罚200金币。
    ATotalPOGCFNC,//10个任务没有完成,共计罚金200金币。
    AdjustSMS,//画面移动速度调节。
    OverGCTTSA,//大于200000金币开始收税，比去年多赚10000金币，收税500金币。
    NeedTITCOGC,//需要增加金币的容量。
    AddOEOEYTCB,//每一年的2月2号增加一名员工。最多可有20名员工。
    EachUWITCOTW,//每次升级都会提升金币的容量，最大等级是12级，增加的容量是2000万金币。
    OnEYTSWIISV,//每年的2月2日商店会结算金币，并增加商品的出售数量，最多新增5倍的出售數量。
    SellIPDTEGC,//每天的出售5件商品，赚取10金币。
    TheQOII,//苹果的数量不足。
    AccumulateGCE,//累计赚取500金币；
    EarnGCA,//每年赚取500金币。
    ThereIAALAOEAP,//已经有大量邮件堆积,请尽快处理！
    DueTLMCNREH,//由于邮箱容量有限,新收邮件已经清除,请整理邮箱!
    NeedTSCTCU,
    GoldCCBRATSF,
}
